import cv2


#this code was generated by claude. python3 webcam_test.py in terminal to run

cap = cv2.VideoCapture(0)

if not cap.isOpened():
    print("ERROR: Could not open webcam.")
else:
    print("Webcam opened! You should see a window. Press Q to quit.")

while cap.isOpened():
    ok, frame = cap.read()
    if not ok:
        print("ERROR: Couldn't read frame.")
        break

    frame = cv2.flip(frame, 1)
    cv2.putText(frame, "Webcam working! Press Q to quit",
                (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
    cv2.imshow("Webcam Test", frame)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
print("Done!")